### ISSUE TITLE
对于 有放回抽样 的解释有瑕疵

### ISSUE THREAD

**Issue by XiaoyuMo92** [AcceptedDoge/machine-learning-yearning-cn#10]
应该是仍需考虑 第一次 选择的 10个 样本。有放回抽样每一次都是在原来的 100 个总体样本上采样的

**Comment by 0xMashiro** [comment]
反馈问题时，最好请带上相应的章节名，这样便于查找确认。

**Comment by 0xMashiro** [comment]
已经将第 32 章中关于有返回抽样与无返回抽样的解释部分更新，感谢你的反馈~
