### ISSUE TITLE
在哪里找到最新的内容观看，或者加入翻译？

### ISSUE THREAD

**Issue by git-cncoder** [AcceptedDoge/machine-learning-yearning-cn#14]
您好，首先感谢作者的编写。
   最新章节已经看完了，我可以在哪里找到最新的内容观看，或者加入翻译？这本书有案例可以做吗？

**Comment by 0xMashiro** [comment]
你好，这本书的翻译即将完成，仅剩下最后的几个章节。
最新的内容可以访问主页的英文站点链接订阅样稿。
这本书最后需要进行中英稿件内容的校对与审核，感兴趣的都可以参与。
本书中提到了许多案例处理的核心思想，需要读者在实际工作中进行实践。
